// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/710/D 2500
// https://codeforces.com/problemset/status/710/problem/D?friends=on
func Test_cf710D(t *testing.T) {
	testCases := [][2]string{
		{
			`2 0 3 3 5 21`,
			`3`,
		},
		{
			`2 4 3 0 6 17`,
			`2`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf710D)
}
