// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/2085/C 1600
// https://codeforces.com/problemset/status/2085/problem/C?friends=on
func Test_cf2085C(t *testing.T) {
	testCases := [][2]string{
		{
			`5
2 5
6 6
19 10
1024 4096
1198372 599188`,
			`0
-1
1
1024
28`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf2085C)
}
