// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/154/D 2400
// https://codeforces.com/problemset/status/154/problem/D?friends=on
func Test_cf154D(t *testing.T) {
	testCases := [][2]string{
		{
			`0 2 0 4`,
			`FIRST
2`,
		},
		{
			`0 2 1 1`,
			`SECOND`,
		},
		{
			`0 2 0 1`,
			`DRAW`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf154D)
}
