// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1780/E 2400
// https://codeforces.com/problemset/status/1780/problem/E?friends=on
func Test_cf1780E(t *testing.T) {
	testCases := [][2]string{
		{
			`7
2 4
16 24
2 6
1 10
3 3
2562 2568
125 100090`,
			`2
6
3
5
0
5
50045`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1780E)
}
