// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1991/C 1300
// https://codeforces.com/problemset/status/1991/problem/C?friends=on
func Test_cf1991C(t *testing.T) {
	testCases := [][2]string{
		{
			`5
1
5
2
0 0
3
4 6 8
4
80 40 20 10
5
1 2 3 4 5`,
			`1
5
0

3
6 1 1
7
60 40 20 10 30 25 5
-1`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1991C)
}
