// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1809/E 2400
// https://codeforces.com/problemset/status/1809/problem/E?friends=on
func Test_cf1809E(t *testing.T) {
	testCases := [][2]string{
		{
			`3 4 4
-2 1 2`,
			`0 0 0 0 0 
0 0 0 0 1 
0 0 1 1 2 
0 1 1 2 3 
1 1 2 3 4`,
		},
		{
			`3 9 5
1 -2 2`,
			`0 0 0 0 0 0 
0 0 0 0 0 1 
0 1 1 1 1 2 
1 2 2 2 2 3 
2 3 3 3 3 4 
3 4 4 4 4 5 
4 5 5 5 5 6 
5 6 6 6 6 7 
6 7 7 7 7 8 
7 7 7 7 8 9`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1809E)
}
