// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/285/E 2600
// https://codeforces.com/problemset/status/285/problem/E?friends=on
func Test_cf285E(t *testing.T) {
	testCases := [][2]string{
		{
			`1 0`,
			`1`,
		},
		{
			`2 1`,
			`0`,
		},
		{
			`3 2`,
			`4`,
		},
		{
			`4 1`,
			`6`,
		},
		{
			`7 4`,
			`328`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf285E)
}
